# Generated by Django 2.1.7 on 2019-03-08 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_auto_20190308_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
