# Generated by Django 2.1.7 on 2019-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.CharField(default='fastfood', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
